# config.yml

#nets

# net:  torchvision.models.segmentation.fcn_resnet50
# net:  torchvision.models.segmentation.fcn_resnet101
# net:  torchvision.models.segmentation.deeplabv3_resnet50
# net:  torchvision.models.segmentation.deeplabv3_resnet101

#weights
weights: "DeepLabV3_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1"
# weights:  DeepLabV3_ResNet50_Weights.COCO_WITH_VOC_LABELS_V1
# weights:  FCN_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1
# weights:  FCN_ResNet50_Weights.COCO_WITH_VOC_LABELS_V1

# DeepLabV3_MobileNet_V3_Large_Weights.COCO_WITH_VOC_LABELS_V1
# LRASPP_MobileNet_V3_Large_Weights.COCO_WITH_VOC_LABELS_V1

batch_size: 16
learning_rate: 0.0001
epochs: 1500
class_weights: [1.0, 10.0]
num_patches: 50

